<?php
/**
 * SystemListsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Retailys
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Retailys API
 *
 * Communication API restful e-commerce system Retailys. Get access in system at [https://www.retailys.com](https://www.retailys.com)<h1>Introduction</h1>**Retailys API** allows to create an amazing ecosystem of e-commerce services and help to develop robust webshops and other e-commerce solutions. Thanks to many built-in omnichannel and multichannel principles, every developer has possibility tu use **Retailys API** for creating vast global e-commerce applications easily and effectively.
 *
 * The version of the OpenAPI document: 1.1.02
 * Contact: helpdesk@retailys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Retailys\Test\Api;

use \Retailys\Configuration;
use \Retailys\ApiException;
use \Retailys\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SystemListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Retailys
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SystemListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCountries
     *
     * Returns countries list in the system..
     *
     */
    public function testGetCountries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrencies
     *
     * Returns currencies list in the system..
     *
     */
    public function testGetCurrencies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLanguages
     *
     * Returns languages list in the system..
     *
     */
    public function testGetLanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentsProvider
     *
     * Find Payments Provider by ID.
     *
     */
    public function testGetPaymentsProvider()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentsProviders
     *
     * Returns Payments Providers list in the system..
     *
     */
    public function testGetPaymentsProviders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipper
     *
     * Find shipper by ID.
     *
     */
    public function testGetShipper()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShippers
     *
     * Returns shippers list in the system..
     *
     */
    public function testGetShippers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getStoresProvider
     *
     * Find Stores Provider by ID.
     *
     */
    public function testGetStoresProvider()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getStoresProviders
     *
     * Returns Stores Providers list in the system..
     *
     */
    public function testGetStoresProviders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
